apiVersion: app/v1
kind: Deployement
metadata:
   name: nginx-deployement
   labels:
     app: nginx
spec:
   replicas: 2
   strategy:
     type: RollingUpdate
     rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
   selector:
     machLabels:
       app: nginx
   template:
     metadata:
       labels:
         app: nginx
     spec:
       containers:
       - name: nginx
         image: rambeloson/nginx:1.1
         ports:
         - containerPort: 80